# Generated by Django 3.0.4 on 2020-06-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Note', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Note', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Note', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Address', models.CharField(max_length=100, unique=True)),
                ('Number', models.IntegerField(null=True, unique=True)),
                ('Email', models.CharField(max_length=100, null=True, unique=True)),
                ('Note', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=100, unique=True)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Mfg', models.DateField(null=True)),
                ('Exp', models.DateField(null=True)),
                ('Details', models.TextField()),
                ('Brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Brand')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalesMan', models.CharField(max_length=100, null=True)),
                ('Number', models.IntegerField(null=True, unique=True)),
                ('Receiver', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('PaymentStatus', models.CharField(max_length=100)),
                ('Outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100, unique=True)),
                ('Owner', models.CharField(max_length=100, null=True, unique=True)),
                ('Number', models.IntegerField(null=True, unique=True)),
                ('Email', models.CharField(max_length=100, null=True, unique=True)),
                ('Address', models.CharField(max_length=100, null=True, unique=True)),
                ('Note', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Note', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalesMan', models.CharField(max_length=100, null=True)),
                ('PurchasePrice', models.FloatField()),
                ('SalePrice', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Product')),
                ('Purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Cost')),
                ('Purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='Supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Unit'),
        ),
    ]
