# Generated by Django 3.0.4 on 2020-06-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200612_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='BrandId',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CategoryId',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='UnitId',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='OutletId',
            new_name='Outlet',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='SupplierId',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='purchasecost',
            old_name='CostId',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='purchasecost',
            old_name='PurchaseId',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='ProductId',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='PurchaseId',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='purchasepayment',
            old_name='PurchaseId',
            new_name='Purchase',
        ),
    ]
