# Generated by Django 3.0.4 on 2020-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200615_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='SalesMan',
        ),
        migrations.AddField(
            model_name='purchase',
            name='Discount',
            field=models.FloatField(null=True),
        ),
    ]
