# Generated by Django 3.0.4 on 2020-06-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200615_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='InvoiceNumber',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
    ]
