# Generated by Django 3.0.4 on 2020-06-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_purchase_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Details',
            field=models.TextField(null=True),
        ),
    ]
