# Generated by Django 3.0.4 on 2020-06-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200617_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='PaymentStatus',
        ),
    ]
