# Generated by Django 3.0.4 on 2020-06-28 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200624_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Outlet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasecost',
            name='Cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasecost',
            name='Purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Purchase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='Purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Purchase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='Purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Purchase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='Outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Outlet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='Sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='Sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sale'),
            preserve_default=False,
        ),
    ]
