# Generated by Django 3.0.4 on 2020-06-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200628_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='InvoiceNumber',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
