# Generated by Django 3.0.4 on 2020-07-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200629_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Receiver',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='SalesMan',
        ),
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='InvoiceNumber',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
