# Generated by Django 3.0.4 on 2020-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200701_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
