# Generated by Django 3.0.4 on 2020-07-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200707_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Outlet'),
        ),
    ]
