# Generated by Django 3.1.4 on 2021-02-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200707_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchasecost',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='salepayment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-id']},
        ),
    ]
